NIP/apps/admin/urls.py
# ！/usr/bin/env python
# -*- coding:utf-8-*-
# File  : urls.py
# Author: TheWu
# Date  : 2020/3/28

"""

"""
from django.urls import path
from . import views

app_name = 'admin'

urlpatterns = [
    path('admin/', views.IndexView.as_view(), name='index'),
    path('admin/tag/', views.TagManageView.as_view(), name='tag'),
    path('admin/tag/<int:tag_id>/', views.TagManageView.as_view(), name='tag_edit'),
    path('admin/tag/<int:tag_id>/news/', views.NewsByTagView.as_view(), name='news_by_tag'),

    path('admin/news/', views.NewsManageView.as_view(), name='news'),
    path('admin/news/<int:news_id>/', views.NewsEditView.as_view(), name='news_edit'),
    path('admin/news/pub/', views.NewsPubView.as_view(), name='news_pub'),

    path('admin/banner/', views.BannerManageView.as_view(), name='banner'),
    path('admin/banner/<int:banner_id>/', views.BannerManageView.as_view(), name='banner_edit'),
    path('admin/banner/add/', views.BannerAddView.as_view(), name='banner_add'),

    path('admin/group/', views.GroupManageView.as_view(), name='group'),
    path('admin/group/<int:g_id>/', views.GroupEditView.as_view(), name='group_edit'),
    path('admin/group/add/', views.GroupAddView.as_view(), name='group_add'),

    path('admin/users/', views.UserManageView.as_view(), name='users'),
    path('admin/users/<int:user_id>/', views.UserEditView.as_view(), name='user_edit'),

    path('admin/upload/', views.UpToServerView.as_view(), name='up_to_server'),
    path('markdown/', views.MarkdownUploadView.as_view(), name='markdown_image_upload'),

]

NIP/apps/news/urls.py
# ！/usr/bin/env python
# -*- coding:utf-8-*-
# File  : urls.py
# Author: TheWu
# Date  : 2020/2/27

"""

"""
from . import views
from django.urls import path

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('news/', views.NewsListView.as_view(), name='news_list'),
    path('news/<int:news_id>/', views.NewsDetailView.as_view(), name='news_detail'),
    path('news/banners/', views.BannerView.as_view(), name='banners'),
    path('news/comments/thumbsup/', views.ThumbsUpView.as_view(), name='thumbs_up'),
    path('news/<int:news_id>/comments/', views.CommentsView.as_view(), name='comments'),
    path('search/', views.SearchView(), name='search'),
    path('voice/', views.WordToVoiceView.as_view(), name='voice'),
]

NIP/apps/users/urls.py
# ！/usr/bin/env python
# -*- coding:utf-8-*-
# File  : urls.py
# Author: TheWu
# Date  : 2020/2/27

"""

"""
from . import views
from django.urls import path

app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('find_pwd/', views.FindPasswordView.as_view(), name='find_pwd'),
    path('change_pwd/', views.ChangePasswordView.as_view(), name='change_pwd'),
    path('fit/', views.UserManageView.as_view(), name='user_set'),
    path('change_mobile/', views.MobileChangeView.as_view(), name='change_mobile'),
    path('index/', views.UserIndexView.as_view(), name='user_index'),

]

NIP/urls.py
# from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from NIP.settings import settings

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('users/', include('users.urls')),
    path('', include('verifications.urls')),
    path('', include('admin.urls')),
    re_path('media/(?P<path>.*)/', serve, {'document_root': settings.MEDIA_ROOT})
]

NIP/apps/admin/models.py
from django.db import models

# Create your models here.

NIP/apps/verifications/models.py
from django.db import models

# Create your models here.

NIP/utils/models.py
# ！/usr/bin/env python
# -*- coding:utf-8-*-
# File  : models.py
# Author: TheWu
# Date  : 2020/2/26

"""

"""
from django.db import models


class ModelBase(models.Model):
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    update_time = models.DateTimeField(auto_now=True, verbose_name='更新时间')
    is_delete = models.BooleanField(default=False, verbose_name='逻辑删除')

    class Meta:
        # 为抽象模型类, 用于其他模型来继承，数据库迁移时不会创建ModelBase表
        abstract = True

NIP/apps/admin/forms.py
# ！/usr/bin/env python
# -*- coding:utf-8-*-
# File  : forms.py
# Author: TheWu
# Date  : 2020/4/12

"""

"""
from django import forms
from news import models


class NewsForm(forms.ModelForm):
    image_url = forms.URLField(label='文章缩略图URL', error_messages={'required': '文章缩略图URL不能为空'})
    tag = forms.ModelChoiceField(queryset=models.Tag.objects.only('id').filter(is_delete=False),
                                 error_messages={'required': '文章分类不能为空'})

    class Meta:
        model = models.News
        fields = ['title', 'digest', 'content', 'image_url', 'tag']

        error_messages = {
            'title': {
                'max_length': '文章标题长度不能大于150',
                'min_length': '文章标题长度不能小于1',
                'required': '文章标题不能为空',
            },
            'digest': {
                'max_length': '文章摘要长度不能大于300',
                'min_length': '文章摘要长度不能小于1',
                'required': '文章摘要不能为空',
            },
            'content': {
                'required': '文本内容不能为空',
            }
        }

NIP/apps/users/forms.py
# ！/usr/bin/env python
# -*- coding:utf-8-*-
# File  : forms.py
# Author: TheWu
# Date  : 2020/3/12

"""

"""
import re
from django import forms
from django.contrib.auth import login
from django.db.models import Q

from users.models import User


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(max_length=20, min_length=6, error_messages={
        'min_length': '密码长度不能小于6位',
        'max_length': '密码长度不能大于20位',
        'required': '密码长度不能为空',
    })
    remember = forms.BooleanField(required=False)

    def __init__(self, **kwargs):
        self.request = kwargs.pop('request')
        super().__init__(**kwargs)

    def clean_username(self):
        user_info = self.cleaned_data.get('username')
        if not user_info:
            raise forms.ValidationError('用户名不能为空')
        if not re.match(r'^[\u4e00-\u9fa5\w_]{2,20}$', user_info):
            raise forms.ValidationError('用户名格式不正确')
        return user_info

    def clean(self):
        clean_data = super().clean()
        user_info = clean_data.get('username')
        password = clean_data.get('password')
        rm = clean_data.get('remember')
        user_qs = User.objects.filter(Q(mobile=user_info) | Q(username=user_info))
        if user_qs:
            user = user_qs.first()
            # 判断密码
            if user.check_password(password):
                if rm:
                    self.request.session.set_expiry(None)
                else:
                    self.request.session.set_expiry(0)
                login(self.request, user)
            else:
                raise forms.ValidationError('用户名或密码错误，请重新输入')
        else:
            raise forms.ValidationError('用户名不存在，请重新输入')

        return clean_data

NIP/apps/admin/views.py
import json
from collections import OrderedDict

from django.contrib.auth.models import Group, Permission
# from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.core.paginator import Paginator, EmptyPage
from django.db.models import Count
from django.http import JsonResponse, HttpResponse, HttpResponseForbidden
from django.shortcuts import render, redirect

# Create your views here.
from django.template.response import SimpleTemplateResponse
from django.utils.decorators import method_decorator
from django.utils.http import urlencode
from django.views import View
from django.views.decorators.csrf import csrf_exempt

from NIP.settings import settings
from NIP.utils import ConstantDefinition
from NIP.utils.fastdfs.fdfs import FDFS_Client
from NIP.utils.res_code import to_json_data, Code, error_map
from admin.forms import NewsForm
from admin.paginator import get_page_data
from news import models
from users.models import User
import logging
from datetime import datetime

logger = logging.getLogger('django')


class LoginRequiredMixin(object):
    @method_decorator(login_required(login_url='/users/login/'))
    def dispatch(self, request, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)


class PermissionRequiredMixin(object):
    permission_required = None

    # login_url = '403.html'

    def method_to_permission(self, request):
        for permission in self.permission_required:
            if request.method.lower() == 'get':
                if 'view' in permission:
                    return permission
            elif request.method.lower() == 'post':
                if 'add' in permission:
                    return permission
            elif request.method.lower() == 'put':
                if 'change' in permission:
                    return permission
            elif request.method.lower() == 'delete':
                if 'delete' in permission:
                    return permission

    def dispatch(self, request, *args, **kwargs):
        if Group.objects.filter(user=request.user).first():
            user_permissions = Group.objects.filter(user=request.user).first().permissions.all()
            user_permissions = [i.content_type.app_label + '.' + i.codename for i in user_permissions]

            local_permission_required = self.method_to_permission(request)
            if local_permission_required not in user_permissions:
                if request.method.lower() == 'get':
                    return render(request, '403.html', context={'errmsg': '很抱歉,您没有权限使用该功能,请联系管理员申请权限！'})
                return to_json_data(errno=Code.ROLEERR, errmsg='您未拥有权限,请向超管申请', data={'redirect_url': '403.html'})
            return super(PermissionRequiredMixin, self).dispatch(request, *args, **kwargs)
        else:
            return render(request, '403.html', context={'errmsg': '很抱歉,您没有权限使用该功能,请联系管理员申请权限！'})


class IndexView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'admin/news/index.html')


class TagManageView(PermissionRequiredMixin, LoginRequiredMixin, View):
    permission_required = ('news.view_tag', 'news.change_tag', 'news.delete_tag', 'news.add_tag')

    def get(self, request):
        tags = models.Tag.objects.values('id', 'name').annotate(num_news=Count('news')).filter(is_delete=False)
        return render(request, 'admin/news/tag_manage.html', locals())

    def post(self, request):
        json_str = request.body
        if not json_str:
            return to_json_data(errno=Code.PARAMERR, errmsg=error_map[Code.PARAMERR])
        dict_data = json.loads(json_str.decode('utf8'))
        name = dict_data.get('name')
        if not name:
            return to_json_data(errno=Code.NODATA, errmsg=error_map[Code.NODATA])
        if len(name) > 20:
            return to_json_data(errno=Code.PARAMERR, errmsg='分类名称请控制在20字内')
        tag = models.Tag.objects.get_or_create(name=name)
        if not tag[-1]:
            if tag[0].is_delete:
                tag[0].is_delete = False
                tag[0].save(update_fields=['is_delete'])
                return to_json_data(errno=Code.OK)
            else:
                return to_json_data(errno=Code.DATAEXIST, errmsg='该分类已存在')
        else:
            return to_json_data(errno=Code.OK)

    def put(self, request, tag_id):

        json_str = request.body
        if not json_str:
            return to_json_data(errno=Code.NODATA, errmsg=error_map[Code.NODATA])
        dict_data = json.loads(json_str.decode('utf8'))
        name = dict_data.get('name').strip()
        if not name:
            return to_json_data(errno=Code.NODATA, errmsg=error_map[Code.NODATA])
        if len(name) > 20:
            return to_json_data(errno=Code.PARAMERR, errmsg='分类名称请控制在20字内')
        tag = models.Tag.objects.get(id=tag_id)
        if tag:
            if not models.Tag.objects.filter(is_delete=False, name=name).exists():
                tag.name = name
                tag.save(update_fields=['name'])
                return to_json_data(errno=Code.OK)
            else:
                return to_json_data(errno=Code.DATAEXIST, errmsg=error_map[Code.DATAEXIST])
        else:
            return to_json_data(errno=Code.PARAMERR, errmsg='该分类不存在')

    def delete(self, request):
        json_str = request.body

        if not json_str:
            return to_json_data(errno=Code.NODATA, errmsg=error_map[Code.NODATA])
        dict_data = json.loads(json_str.decode('utf-8'))
        tag_id = dict_data.get('tag_id')
        if not tag_id:
            return to_json_data(errno=Code.NODATA, errmsg=error_map[Code.NODATA])
        if type(tag_id) == type(list()):
            tag_list = []
            for id in tag_id:
                tag = models.Tag.objects.get(is_delete=False, id=id)
                if tag:
                    if models.Tag.objects.values('id').annotate(num_news=Count('news')).filter(is_delete=False, id=id). \
                            get()['num_news']:
                        return to_json_data(errno=Code.NODATA, errmsg='文章数量不为零的分类不允许删除')
                    tag_list.append(tag)
                else:
                    return to_json_data(errno=Code.NODATA, errmsg='分类信息不存在')
            for tag in tag_list:
                tag.is_delete = True
                tag.save(update_fields=['is_delete'])

            return to_json_data(errno=Code.OK)
        else:
            tag = models.Tag.objects.get(id=tag_id)
            if tag:
                if models.Tag.objects.values('id').annotate(num_news=Count('news')).filter(is_delete=False, id=tag_id). \
                        get()['num_news']:
                    return to_json_data(errno=Code.NODATA, errmsg='文章数量不为零的分类不允许删除')
                else:
                    tag.is_delete = True
                    tag.save(update_fields=['is_delete'])
                    return to_json_data(errno=Code.OK)
            else:
                return to_json_data(errno=Code.PARAMERR, errmsg='该分类不存在')


class NewsByTagView(View):
    def get(self, request, tag_id):
        news = models.News.objects.values('id', 'title').filter(is_delete=False, tag_id=tag_id)
        news_list = [i for i in news]
        return to_json_data(data={'news': news_list})


class NewsManageView(PermissionRequiredMixin, LoginRequiredMixin, View):
    permission_required = ('news.view_news', 'news.delete_news')

    def get(self, request):
        start_time = request.GET.get('start_time', '')
        start_time = datetime.strptime(start_time, '%Y/%m/%d') if start_time else ''
        end_time = request.GET.get('end_time', '')
        end_time = datetime.strptime(end_time, '%Y/%m/%d') if end_time else ''
        if start_time > end_time:
            start_time, end_time = end_time, start_time
        news = models.News.objects.only('title', 'update_time', 'tag__name', 'author__username').filter(
            is_delete=False)
        if start_time and not end_time:
            news = news.filter(update_time__gte=start_time)
        if not start_time and end_time:
            news = news.filter(update_time__lte=end_time)
        if start_time and end_time:
            news = news.filter(update_time__gte=start_time, update_time__lte=end_time)
        title = request.GET.get('title', '')

        if title:
            news = news.filter(title__icontains=title)
        author = request.GET.get('author', '')
        if author:
            news = news.filter(author__username__icontains=author)
        tags = models.Tag.objects.only('name').filter(is_delete=False)
        tag = int(request.GET.get('tag_id', 0))
        news = news.filter(tag_id=tag, is_delete=False) or news.filter(is_delete=False)
        try:
            page = request.GET.get('page', 1)
        except Exception as e:
            logger.error('页面参数异常：\n{}'.format(e))
            page = 1

        pages = Paginator(news, 10)

        try:
            news_info = pages.page(page)
        except EmptyPage:
            logger.error('页码错误')
            news_info = pages.page(pages.num_pages)
        pages_data = get_page_data(pages, news_info, 1)
        start_time = start_time.strftime('%Y/%m/%d') if start_time else ''
        end_time = end_time.strftime('%Y/%m/%d') if start_time else ''

        data = {
            'news': news_info,
            'tags': tags,
            'paginator': pages,
            'start_time': start_time,
            'end_time': end_time,
            'title': title,
            'author': author,
            'tag_id': tag,
            'other_params': urlencode({
                'start_time': start_time,
                'end_time': end_time,
                'title': title,
                'author': author,
                'tag_id': tag
            })
        }
        data.update(pages_data)
        return render(request, 'admin/news/news_manage.html', context=data)

NIP/templates/users/change_password.html
{% extends 'base/base.html' %}
{% block title %}修改密码{% endblock %}
{% block link %}
    <link rel="stylesheet" href="../../static/css/users/auth.css">
    <link rel="stylesheet" href="../../static/css/users/change_pwd.css">


{% endblock %}
{% block main %}
    <!-- container start -->
    <main id="container">
        <div class="register-contain">
            <div class="top-contain">
                <h4 class="please-register">修改密码</h4>

            </div>
            <form action="" method="post" class="form-contain">
                <div class="form-item">
                    <input type="tel" placeholder="请输入手机号" id="mobile" name="telephone" class="form-control"
                           autocomplete="off" autofocus>
                </div>
                <div class="form-item">
                    <input type="text" placeholder="请输入短信验证码" name="sms_captcha" class="form-captcha" id="input_smscode"
                           autocomplete="off">
                    <a href="javascript:void(0);" class="sms-captcha" title="发送验证码">获取短信验证码</a>
                </div>
                <!-- 按钮触发模态框 -->
                <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal"
                        id="modal_btn">确定
                </button>
                <!-- 模态框（Modal） -->
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
                     aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;
                                </button>
                                <h4 class="modal-title" id="myModalLabel">修改密码</h4>
                            </div>
                            <div class="modal-body">
                                <div class="form-item">
                                    <input type="password" placeholder="请输入原始密码" id="old_pwd" name="old_password"
                                           class="form-control"
                                           autocomplete="off" autofocus>
                                </div>
                                <div class="form-item">
                                    <input type="password" placeholder="请输入新密码" id="pwd" name="password"
                                           class="form-control">
                                </div>
                                <div class="form-item">
                                    <input type="password" placeholder="请再次输入新密码" name="password_repeat"
                                           class="form-control">
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default cancel-btn" data-dismiss="modal">关闭
                                </button>
                                <div class="form-item">
                                    <input type="submit" value="确定" class="btn btn-primary submit-btn">
                                </div>

                            </div>
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal -->
                </div>

            </form>
        </div>
    </main>
    <!-- container end -->


{% endblock %}

{% block script %}
    <script src="{% static 'js/users/change_pwd.js' %}"></script>
{% endblock %}

NIP/templates/users/index.html
{% extends 'base/base.html' %}
{% block title %}新闻资讯-个人主页{% endblock %}
{% block link %}
    <link rel="stylesheet" href="../../static/css/users/user_index.css">
    <link rel="stylesheet" type="text/css" href="http://at.alicdn.com/t/font_1698819_exvvpdti8m9.css">
{% endblock %}
{% load data_filter %}
{% block main %}
    <div class="container">
        <div class="main">
            <div class="main-top">
                <a class="avatar" href="{% url 'users:user_index' %}">
                    <img src="{{ user.avatar_url }}" alt="">
                </a>
                <div class="title">
                    <a class="name" href="{% url 'users:user_index' %}">{{ user.username }}</a>
                </div>
                <div class="info">
                    <ul>
                        <li>
                            <div class="meta-block">
                                <a href="#">
                                    <p>{{ article_count }}</p>
                                    文章
                                </a>
                            </div>
                        </li>
                        <li>
                            <div class="meta-block">
                                <a href="#">
                                    <p>{{ thumb_count }}</p>
                                    点赞
                                </a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="outer_container">
                <ul class="trigger-menu">
                    <li class="active" data-id="0"><a href=""><i class="fa fa-bell"></i>动态</a></li>
{#                    <li data-id="1"><a href=""><i class="fa fa-comments"></i>最新评论</a></li>#}
                    {#                    <li data-id="2"><a href=""><i class="fa fa-book"></i>文章</a></li>#}
                </ul>
                <div id="list_container">
                    <ul class="note-list">
                        {% for comment in comments %}
                            <li>
                                <div class="contents">
                                    <div class="author">
                                        <a class="avatar" href="{% url 'users:user_index' %}">
                                            <img src="{{ user.avatar_url }}" alt="">
                                        </a>
                                        <div class="info">
                                            <a class="nickname"
                                               href="{% url 'users:user_index' %}">{{ user.username }}</a>
                                            <span class="comment-note" data-datetime="{{ comment.update_time }}">
                                            {% if comment.content %}
                                                发表
                                            {% else %}
                                                赞
                                            {% endif %}
                                                了评论
                                            {{ comment.update_time|user_time_filter }}
                                            </span>
                                        </div>
                                    </div>
                                    <p class="comment">
                                        {% if comment.content %}
                                            {{ comment.content }}
                                        {% else %}
                                            {{ comment.comments.content }}
                                        {% endif %}
                                    </p>
                                    <blockquote>
                                        {% if comment.content %}
                                            <a class="title"
                                               href="/news/{{ comment.news.id }}">{{ comment.news.title }}</a>
                                            <p class="abstract">{{ comment.news.digest }}</p>
                                            <div class="meta">
                                                <p class="origin-author">{{ comment.news.author.username }}</p>
                                                <a href="/news/{{ comment.news.id }}"><i
                                                        class="glyphicon glyphicon-eye-open"></i>{{ comment.news.clicks }}
                                                </a>
                                                <a href="/news/{{ comment.news.id }}"><i
                                                        class="glyphicon glyphicon-comment"></i>{{ comment.news_comment_count }}
                                                </a>
                                                <span><i class="iconfont icon-zan"
                                                         style="font-size: 12px"></i>{{ comment.news_thumb_count }}</span>
                                            </div>
                                        {% else %}
                                            <div class="origin-author">
                                                <a href="#">{{ comment.comments.author.username }}</a>
                                                <span>评论自<a
                                                        href="/news/{{ comment.comments.news.id }}">{{ comment.comments.news.title }}</a></span>
                                            </div>
                                        {% endif %}

                                    </blockquote>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script src="../../static/js/users/index.js"></script>
{% endblock %}

NIP/templates/users/login.html
{% extends 'base/base.html' %}
{% block link %}
    <link rel="stylesheet" href="../../static/css/users/auth.css">
{% endblock %}
{% block main %}
    <!-- container start -->
    <main id="container">
        <div class="login-contain">
            <div class="top-contain">
                <h4 class="please-login">请登录</h4>
                <a href="{% url 'users:register' %}" class="register">立即注册 &gt;</a>
            </div>
            <form action="" method="post" class="form-contain">
                <div class="form-item">
                    <input type="tel" placeholder="请输入用户名或手机号" name="telephone" class="form-control" autocomplete="off">
                </div>
                <div class="form-item">
                    <input type="password" placeholder="请输入密码" name="password" class="form-control">
                </div>
                <div class="form-item clearfix">
                    <label>
                        <input type="checkbox" name="remember">
                        <span>记住我</span>
                    </label>
                    <a href="{% url 'users:find_pwd' %}" class="forget-password">忘记密码?</a>
                </div>
                <div class="form-login">
                    <input type="submit" value="登录" class="login-btn">
                </div>
            </form>
        </div>
    </main>
    <!-- container end -->

{% endblock %}

{% block script %}
    <script src="{% static 'js/users/login.js' %}"></script>
{% endblock %}

NIP/templates/users/register.html
{% extends 'base/base.html' %}
{% block link %}
    <link rel="stylesheet" href="../../static/css/users/auth.css">

{% endblock %}
{% block main %}
    <!-- container start -->
    <main id="container">
        <div class="register-contain">
            <div class="top-contain">
                <h4 class="please-register">请注册</h4>
                <a href="{% url 'users:login' %}" class="login">立即登录 &gt;</a>
            </div>
            <form action="" method="post" class="form-contain">


                <div class="form-item">
                    <input type="text" placeholder="请输入用户名" id="user_name" name="username" class="form-control"
                           autocomplete="off">
                </div>
                <div class="form-item">
                    <input type="password" placeholder="请输入密码" id="pwd" name="password" class="form-control">
                </div>
                <div class="form-item">
                    <input type="password" placeholder="请输入确认密码" name="password_repeat" class="form-control">
                </div>
                <div class="form-item">
                    <input type="tel" placeholder="请输入手机号" id="mobile" name="telephone" class="form-control"
                           autocomplete="off" autofocus>
                </div>
                <div class="form-item">
                    <input type="text" placeholder="请输入图形验证码" id="input_captcha" name="captcha_graph"
                           class="form-captcha">
                    <a href="javascript:void(0);" class="captcha-graph-img">
                        <img src="" alt="验证码" title="点击刷新">
                    </a>
                </div>
                <div class="form-item">
                    <input type="text" placeholder="请输入短信验证码" name="sms_captcha" class="form-captcha" id="input_smscode"
                           autocomplete="off">
                    <a href="javascript:void(0);" class="sms-captcha" title="发送验证码">获取短信验证码</a>
                </div>
                <div class="form-item">
                    <input type="submit" value="立即注册" class="register-btn">
                </div>
            </form>
        </div>
    </main>
    <!-- container end -->


{% endblock %}

{% block script %}
    <script src="{% static 'js/users/register.js' %}"></script>
{% endblock %}