NIP/apps/admin/urls.py
# ！/usr/bin/env python
# -*- coding:utf-8-*-
# File  : urls.py
# Author: TheWu
# Date  : 2020/3/28

"""

"""
from django.urls import path
from . import views

app_name = 'admin'

urlpatterns = [
    path('admin/', views.IndexView.as_view(), name='index'),
    path('admin/tag/', views.TagManageView.as_view(), name='tag'),
    path('admin/tag/<int:tag_id>/', views.TagManageView.as_view(), name='tag_edit'),
    path('admin/tag/<int:tag_id>/news/', views.NewsByTagView.as_view(), name='news_by_tag'),

    path('admin/news/', views.NewsManageView.as_view(), name='news'),
    path('admin/news/<int:news_id>/', views.NewsEditView.as_view(), name='news_edit'),
    path('admin/news/pub/', views.NewsPubView.as_view(), name='news_pub'),

    path('admin/banner/', views.BannerManageView.as_view(), name='banner'),
    path('admin/banner/<int:banner_id>/', views.BannerManageView.as_view(), name='banner_edit'),
    path('admin/banner/add/', views.BannerAddView.as_view(), name='banner_add'),

    path('admin/group/', views.GroupManageView.as_view(), name='group'),
    path('admin/group/<int:g_id>/', views.GroupEditView.as_view(), name='group_edit'),
    path('admin/group/add/', views.GroupAddView.as_view(), name='group_add'),

    path('admin/users/', views.UserManageView.as_view(), name='users'),
    path('admin/users/<int:user_id>/', views.UserEditView.as_view(), name='user_edit'),

    path('admin/upload/', views.UpToServerView.as_view(), name='up_to_server'),
    path('markdown/', views.MarkdownUploadView.as_view(), name='markdown_image_upload'),

]

NIP/apps/news/urls.py
# ！/usr/bin/env python
# -*- coding:utf-8-*-
# File  : urls.py
# Author: TheWu
# Date  : 2020/2/27

"""

"""
from . import views
from django.urls import path

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('news/', views.NewsListView.as_view(), name='news_list'),
    path('news/<int:news_id>/', views.NewsDetailView.as_view(), name='news_detail'),
    path('news/banners/', views.BannerView.as_view(), name='banners'),
    path('news/comments/thumbsup/', views.ThumbsUpView.as_view(), name='thumbs_up'),
    path('news/<int:news_id>/comments/', views.CommentsView.as_view(), name='comments'),
    path('search/', views.SearchView(), name='search'),
    path('voice/', views.WordToVoiceView.as_view(), name='voice'),
]

NIP/apps/users/urls.py
# ！/usr/bin/env python
# -*- coding:utf-8-*-
# File  : urls.py
# Author: TheWu
# Date  : 2020/2/27

"""

"""
from . import views
from django.urls import path

app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('find_pwd/', views.FindPasswordView.as_view(), name='find_pwd'),
    path('change_pwd/', views.ChangePasswordView.as_view(), name='change_pwd'),
    path('fit/', views.UserManageView.as_view(), name='user_set'),
    path('change_mobile/', views.MobileChangeView.as_view(), name='change_mobile'),
    path('index/', views.UserIndexView.as_view(), name='user_index'),

]

NIP/urls.py
# from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from NIP.settings import settings

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('users/', include('users.urls')),
    path('', include('verifications.urls')),
    path('', include('admin.urls')),
    re_path('media/(?P<path>.*)/', serve, {'document_root': settings.MEDIA_ROOT})
]

NIP/apps/admin/models.py
from django.db import models

# Create your models here.

NIP/apps/verifications/models.py
from django.db import models

# Create your models here.

NIP/utils/models.py
# ！/usr/bin/env python
# -*- coding:utf-8-*-
# File  : models.py
# Author: TheWu
# Date  : 2020/2/26

"""

"""
from django.db import models


class ModelBase(models.Model):
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    update_time = models.DateTimeField(auto_now=True, verbose_name='更新时间')
    is_delete = models.BooleanField(default=False, verbose_name='逻辑删除')

    class Meta:
        # 为抽象模型类, 用于其他模型来继承，数据库迁移时不会创建ModelBase表
        abstract = True

NIP/apps/admin/forms.py
# ！/usr/bin/env python
# -*- coding:utf-8-*-
# File  : forms.py
# Author: TheWu
# Date  : 2020/4/12

"""

"""
from django import forms
from news import models


class NewsForm(forms.ModelForm):
    image_url = forms.URLField(label='文章缩略图URL', error_messages={'required': '文章缩略图URL不能为空'})
    tag = forms.ModelChoiceField(queryset=models.Tag.objects.only('id').filter(is_delete=False),
                                 error_messages={'required': '文章分类不能为空'})

    class Meta:
        model = models.News
        fields = ['title', 'digest', 'content', 'image_url', 'tag']

        error_messages = {
            'title': {
                'max_length': '文章标题长度不能大于150',
                'min_length': '文章标题长度不能小于1',
                'required': '文章标题不能为空',
            },
            'digest': {
                'max_length': '文章摘要长度不能大于300',
                'min_length': '文章摘要长度不能小于1',
                'required': '文章摘要不能为空',
            },
            'content': {
                'required': '文本内容不能为空',
            }
        }

NIP/apps/users/forms.py
# ！/usr/bin/env python
# -*- coding:utf-8-*-
# File  : forms.py
# Author: TheWu
# Date  : 2020/3/12

"""

"""
import re
from django import forms
from django.contrib.auth import login
from django.db.models import Q

from users.models import User


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(max_length=20, min_length=6, error_messages={
        'min_length': '密码长度不能小于6位',
        'max_length': '密码长度不能大于20位',
        'required': '密码长度不能为空',
    })
    remember = forms.BooleanField(required=False)

    def __init__(self, **kwargs):
        self.request = kwargs.pop('request')
        super().__init__(**kwargs)

    def clean_username(self):
        user_info = self.cleaned_data.get('username')
        if not user_info:
            raise forms.ValidationError('用户名不能为空')
        if not re.match(r'^[\u4e00-\u9fa5\w_]{2,20}$', user_info):
            raise forms.ValidationError('用户名格式不正确')
        return user_info

    def clean(self):
        clean_data = super().clean()
        user_info = clean_data.get('username')
        password = clean_data.get('password')
        rm = clean_data.get('remember')
        user_qs = User.objects.filter(Q(mobile=user_info) | Q(username=user_info))
        if user_qs:
            user = user_qs.first()
            # 判断密码
            if user.check_password(password):
                if rm:
                    self.request.session.set_expiry(None)
                else:
                    self.request.session.set_expiry(0)
                login(self.request, user)
            else:
                raise forms.ValidationError('用户名或密码错误，请重新输入')
        else:
            raise forms.ValidationError('用户名不存在，请重新输入')

        return clean_data

NIP/apps/admin/views.py
import json
from collections import OrderedDict

from django.contrib.auth.models import Group, Permission
# from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.core.paginator import Paginator, EmptyPage
from django.db.models import Count
from django.http import JsonResponse, HttpResponse, HttpResponseForbidden
from django.shortcuts import render, redirect

# Create your views here.
from django.template.response import SimpleTemplateResponse
from django.utils.decorators import method_decorator
from django.utils.http import urlencode
from django.views import View
from django.views.decorators.csrf import csrf_exempt

from NIP.settings import settings
from NIP.utils import ConstantDefinition
from NIP.utils.fastdfs.fdfs import FDFS_Client
from NIP.utils.res_code import to_json_data, Code, error_map
from admin.forms import NewsForm
from admin.paginator import get_page_data
from news import models
from users.models import User
import logging
from datetime import datetime

logger = logging.getLogger('django')


class LoginRequiredMixin(object):
    @method_decorator(login_required(login_url='/users/login/'))
    def dispatch(self, request, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)


class PermissionRequiredMixin(object):
    permission_required = None

    # login_url = '403.html'

    def method_to_permission(self, request):
        for permission in self.permission_required:
            if request.method.lower() == 'get':
                if 'view' in permission:
                    return permission
            elif request.method.lower() == 'post':
                if 'add' in permission:
                    return permission
            elif request.method.lower() == 'put':
                if 'change' in permission:
                    return permission
            elif request.method.lower() == 'delete':
                if 'delete' in permission:
                    return permission

    def dispatch(self, request, *args, **kwargs):
        if Group.objects.filter(user=request.user).first():
            user_permissions = Group.objects.filter(user=request.user).first().permissions.all()
            user_permissions = [i.content_type.app_label + '.' + i.codename for i in user_permissions]

            local_permission_required = self.method_to_permission(request)
            if local_permission_required not in user_permissions:
                if request.method.lower() == 'get':
                    return render(request, '403.html', context={'errmsg': '很抱歉,您没有权限使用该功能,请联系管理员申请权限！'})
                return to_json_data(errno=Code.ROLEERR, errmsg='您未拥有权限,请向超管申请', data={'redirect_url': '403.html'})
            return super(PermissionRequiredMixin, self).dispatch(request, *args, **kwargs)
        else:
            return render(request, '403.html', context={'errmsg': '很抱歉,您没有权限使用该功能,请联系管理员申请权限！'})


class IndexView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'admin/news/index.html')


class TagManageView(PermissionRequiredMixin, LoginRequiredMixin, View):
    permission_required = ('news.view_tag', 'news.change_tag', 'news.delete_tag', 'news.add_tag')

    def get(self, request):
        tags = models.Tag.objects.values('id', 'name').annotate(num_news=Count('news')).filter(is_delete=False)
        return render(request, 'admin/news/tag_manage.html', locals())

    def post(self, request):
        json_str = request.body
        if not json_str:
            return to_json_data(errno=Code.PARAMERR, errmsg=error_map[Code.PARAMERR])
        dict_data = json.loads(json_str.decode('utf8'))
        name = dict_data.get('name')
        if not name:
            return to_json_data(errno=Code.NODATA, errmsg=error_map[Code.NODATA])
        if len(name) > 20:
            return to_json_data(errno=Code.PARAMERR, errmsg='分类名称请控制在20字内')
        tag = models.Tag.objects.get_or_create(name=name)
        if not tag[-1]:
            if tag[0].is_delete:
                tag[0].is_delete = False
                tag[0].save(update_fields=['is_delete'])
                return to_json_data(errno=Code.OK)
            else:
                return to_json_data(errno=Code.DATAEXIST, errmsg='该分类已存在')
        else:
            return to_json_data(errno=Code.OK)

    def put(self, request, tag_id):

        json_str = request.body
        if not json_str:
            return to_json_data(errno=Code.NODATA, errmsg=error_map[Code.NODATA])
        dict_data = json.loads(json_str.decode('utf8'))
        name = dict_data.get('name').strip()
        if not name:
            return to_json_data(errno=Code.NODATA, errmsg=error_map[Code.NODATA])
        if len(name) > 20:
            return to_json_data(errno=Code.PARAMERR, errmsg='分类名称请控制在20字内')
        tag = models.Tag.objects.get(id=tag_id)
        if tag:
            if not models.Tag.objects.filter(is_delete=False, name=name).exists():
                tag.name = name
                tag.save(update_fields=['name'])
                return to_json_data(errno=Code.OK)
            else:
                return to_json_data(errno=Code.DATAEXIST, errmsg=error_map[Code.DATAEXIST])
        else:
            return to_json_data(errno=Code.PARAMERR, errmsg='该分类不存在')

    def delete(self, request):
        json_str = request.body

        if not json_str:
            return to_json_data(errno=Code.NODATA, errmsg=error_map[Code.NODATA])
        dict_data = json.loads(json_str.decode('utf-8'))
        tag_id = dict_data.get('tag_id')
        if not tag_id:
            return to_json_data(errno=Code.NODATA, errmsg=error_map[Code.NODATA])
        if type(tag_id) == type(list()):
            tag_list = []
            for id in tag_id:
                tag = models.Tag.objects.get(is_delete=False, id=id)
                if tag:
                    if models.Tag.objects.values('id').annotate(num_news=Count('news')).filter(is_delete=False, id=id). \
                            get()['num_news']:
                        return to_json_data(errno=Code.NODATA, errmsg='文章数量不为零的分类不允许删除')
                    tag_list.append(tag)
                else:
                    return to_json_data(errno=Code.NODATA, errmsg='分类信息不存在')
            for tag in tag_list:
                tag.is_delete = True
                tag.save(update_fields=['is_delete'])

            return to_json_data(errno=Code.OK)
        else:
            tag = models.Tag.objects.get(id=tag_id)
            if tag:
                if models.Tag.objects.values('id').annotate(num_news=Count('news')).filter(is_delete=False, id=tag_id). \
                        get()['num_news']:
                    return to_json_data(errno=Code.NODATA, errmsg='文章数量不为零的分类不允许删除')
                else:
                    tag.is_delete = True
                    tag.save(update_fields=['is_delete'])
                    return to_json_data(errno=Code.OK)
            else:
                return to_json_data(errno=Code.PARAMERR, errmsg='该分类不存在')


class NewsByTagView(View):
    def get(self, request, tag_id):
        news = models.News.objects.values('id', 'title').filter(is_delete=False, tag_id=tag_id)
        news_list = [i for i in news]
        return to_json_data(data={'news': news_list})


class NewsManageView(PermissionRequiredMixin, LoginRequiredMixin, View):
    permission_required = ('news.view_news', 'news.delete_news')

    def get(self, request):
        start_time = request.GET.get('start_time', '')
        start_time = datetime.strptime(start_time, '%Y/%m/%d') if start_time else ''
        end_time = request.GET.get('end_time', '')
        end_time = datetime.strptime(end_time, '%Y/%m/%d') if end_time else ''
        if start_time > end_time:
            start_time, end_time = end_time, start_time
        news = models.News.objects.only('title', 'update_time', 'tag__name', 'author__username').filter(
            is_delete=False)
        if start_time and not end_time:
            news = news.filter(update_time__gte=start_time)
        if not start_time and end_time:
            news = news.filter(update_time__lte=end_time)
        if start_time and end_time:
            news = news.filter(update_time__gte=start_time, update_time__lte=end_time)
        title = request.GET.get('title', '')

        if title:
            news = news.filter(title__icontains=title)
        author = request.GET.get('author', '')
        if author:
            news = news.filter(author__username__icontains=author)
        tags = models.Tag.objects.only('name').filter(is_delete=False)
        tag = int(request.GET.get('tag_id', 0))
        news = news.filter(tag_id=tag, is_delete=False) or news.filter(is_delete=False)
        try:
            page = request.GET.get('page', 1)
        except Exception as e:
            logger.error('页面参数异常：\n{}'.format(e))
            page = 1

        pages = Paginator(news, 10)

        try:
            news_info = pages.page(page)
        except EmptyPage:
            logger.error('页码错误')
            news_info = pages.page(pages.num_pages)
        pages_data = get_page_data(pages, news_info, 1)
        start_time = start_time.strftime('%Y/%m/%d') if start_time else ''
        end_time = end_time.strftime('%Y/%m/%d') if start_time else ''

        data = {
            'news': news_info,
            'tags': tags,
            'paginator': pages,
            'start_time': start_time,
            'end_time': end_time,
            'title': title,
            'author': author,
            'tag_id': tag,
            'other_params': urlencode({
                'start_time': start_time,
                'end_time': end_time,
                'title': title,
                'author': author,
                'tag_id': tag
            })
        }
        data.update(pages_data)
        return render(request, 'admin/news/news_manage.html', context=data)

NIP/templates/news/list.html
{% extends 'base/base.html' %}

{% block title %}列表页{% endblock %}
{% load news_template %}
{% load data_filter %}
{% block link %}
    <link rel="stylesheet" type="text/css" href="../../static/css/news/list.css"/>

{% endblock %}

{% block main-contain %}
    <div class="content">
        {% if not show %}
            <div class="title">
                <h3 style="line-height: 1.3">搜索结果
                    <span style="font-weight: 700;color: #ff6620;">{{ context.paginator.num_pages }}</span>页</h3>
            </div>
            {% load highlight %}
            {% for one_news in context.page.object_list %}
                <article class="excerpt excerpt-1">
                    <a class="focus" href="{% url 'news:news_detail' one_news.id %}" target="_blank">
                        <img class="thumb" data-original="{{ one_news.image_url }}"
                             src="{{ one_news.image_url }}" alt="{{ one_news.title }}"
                             style="display: inline;">
                    </a>
                    <header>
                        <a class="cat" href="#" title="MZ-NetBlog主题">{{ one_news.tag.name }}<i></i></a>
                        <h2>
                            <a href="{% url 'news:news_detail' one_news.id %}"
                               target="_blank">{% highlight one_news.title with query %}</a>
                        </h2>
                    </header>
                    <p class="meta">
                        <time class="time"><i
                                class="glyphicon glyphicon-time"></i> {{ one_news.update_time|date:'Y-m-d' }}</time>
                        <span class="views"><i class="glyphicon glyphicon-eye-open"></i> {{ one_news.clicks }}</span>
                        <a class="comment" href="##comment" title="评论" target="_blank">
                            <i class="glyphicon glyphicon-comment"></i> 4</a>
                    </p>
                    <p class="note">{% highlight one_news.digest with query %}</p>
                </article>
            {% endfor %}

        {% else %}
            <div class="title">
                <h3 style="line-height: 1.3">最新文章</h3>
            </div>
            {% for one_news in page.object_list %}
                <article class="excerpt excerpt-1">
                    <a class="focus" href="{% url 'news:news_detail' one_news.id %}" target="_blank">
                        <img class="thumb" data-original="{{ one_news.image_url }}"
                             src="{{ one_news.image_url }}" alt="{{ one_news.title }}"
                             style="display: inline;">
                    </a>
                    <header>
                        <a class="cat" href="#" title="MZ-NetBlog主题">{{ one_news.tag.name }}<i></i></a>
                        <h2>
                            <a href="{% url 'news:news_detail' one_news.id %}" target="_blank">{{ one_news.title }}</a>
                        </h2>
                    </header>
                    <p class="meta">
                        <time class="time"><i
                                class="glyphicon glyphicon-time"></i> {{ one_news.update_time|date:'Y-m-d' }}</time>
                        <span class="views"><i class="glyphicon glyphicon-eye-open"></i> {{ one_news.clicks }}</span>
                        <a class="comment" href="##comment" title="评论" target="_blank">
                            <i class="glyphicon glyphicon-comment"></i> 4</a>
                    </p>
                    <p class="note">{{ one_news.digest }}</p>
                </article>
            {% endfor %}
        {% endif %}


        {#        分页#}
        <nav class="pagination">
            <div class="pagebar" id="pageBar">
                {% if not show %}
                    {% if context.page.has_previous %}
                        {% if query %}
                            <a href="{% url 'news:search' %}?q={{ query }}&amp;page={{ context.page.previous_page_number }}&q={{ query }}"
                               class="prev">上一页</a>
                        {% else %}
                            <a href="{% url 'news:search' %}?page={{ context.page.previous_page_number }}" class="prev">上一页</a>
                        {% endif %}
                    {% endif %}


                    {#                          列出所有的URL地址 页码#}
                    {% if context.page.has_previous or context.page.has_next %}

                        {% for n in context.page|page_bar %}
                            {% if query %}
                                {% if n == '...' %}
                                    <span class="point">{{ n }}</span>
                                {% else %}
                                    {% if n == context.page.number %}
                                        <span class="sel">{{ n }}</span>
                                    {% else %}
                                        <a href="{% url 'news:search' %}?page={{ n }}&q={{ query }}">{{ n }}</a>
                                    {% endif %}
                                {% endif %}
                            {% else %}
                                {% if n == '...' %}
                                    <span class="point">{{ n }}</span>
                                {% else %}
                                    {% if n == context.page.number %}
                                        <span class="sel">{{ n }}</span>
                                    {% else %}
                                        <a href="{% url 'news:search' %}?page={{ n }}">{{ n }}</a>
                                    {% endif %}
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    {% endif %}

                    {#                       next_page 下一页的URL地址#}
                    {% if context.page.has_next %}
                        {% if query %}
                            <a href="{% url 'news:search' %}?q={{ query }}&amp;page={{ context.page.next_page_number }}&q={{ query }}"
                               class="next">下一页</a>
                        {% else %}
                            <a href="{% url 'news:search' %}?page={{ context.page.next_page_number }}"
                               class="next">下一页</a>
                        {% endif %}
                    {% endif %}
                {% else %}
                    {% if page.has_previous %}
                        {% if query %}
                            <a href="{% url 'news:search' %}?q={{ query }}&amp;page={{ page.previous_page_number }}&q={{ query }}"
                               class="prev">上一页</a>
                        {% else %}
                            <a href="{% url 'news:search' %}?page={{ page.previous_page_number }}" class="prev">上一页</a>
                        {% endif %}
                    {% endif %}


                    {#                          列出所有的URL地址 页码#}
                    {% if page.has_previous or page.has_next %}

                        {% for n in page|page_bar %}
                            {% if query %}
                                {% if n == '...' %}
                                    <span class="point">{{ n }}</span>
                                {% else %}
                                    {% if n == page.number %}
                                        <span class="sel">{{ n }}</span>
                                    {% else %}
                                        <a href="{% url 'news:search' %}?page={{ n }}&q={{ query }}">{{ n }}</a>
                                    {% endif %}
                                {% endif %}
                            {% else %}
                                {% if n == '...' %}
                                    <span class="point">{{ n }}</span>
                                {% else %}
                                    {% if n == page.number %}
                                        <span class="sel">{{ n }}</span>
                                    {% else %}
                                        <a href="{% url 'news:search' %}?page={{ n }}">{{ n }}</a>
                                    {% endif %}
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    {% endif %}

                    {#                       next_page 下一页的URL地址#}
                    {% if page.has_next %}
                        {% if query %}
                            <a href="{% url 'news:search' %}?q={{ query }}&amp;page={{ page.next_page_number }}&q={{ query }}"
                               class="next">下一页</a>
                        {% else %}
                            <a href="{% url 'news:search' %}?page={{ page.next_page_number }}" class="next">下一页</a>
                        {% endif %}
                    {% endif %}
                {% endif %}
            </div>
        </nav>
    </div>
{% endblock %}
{% block side %}
    <aside class="sidebar">
        <div class="fixed">
            <div class="widget widget-tabs">
                <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active"><a href="#notice" aria-controls="notice" role="tab"
                                                              data-toggle="tab">统计信息</a></li>
                    <li role="presentation"><a href="#contact" aria-controls="contact" role="tab"
                                               data-toggle="tab">联系站长</a></li>
                </ul>
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane contact active" id="notice">
                        <h2>文章总数:
                            {{ num_news }} 篇
                        </h2>
                        {#                        <h2>网站运行:#}
                        {#                            <span id="sitetime">88天 </span></h2>#}
                    </div>
                    <div role="tabpanel" class="tab-pane contact" id="contact">
                        <h2>QQ:
                            <a href="" target="_blank" rel="nofollow" data-toggle="tooltip"
                               data-placement="bottom"
                               title="" data-original-title="QQ:">1316983101</a>
                        </h2>
                        <h2>Email:
                            <a href="#" target="_blank" data-toggle="tooltip" rel="nofollow"
                               data-placement="bottom"
                               title="" data-original-title="#">1316983101@qq.com</a></h2>
                    </div>
                </div>
            </div>
            <div class="widget widget_search">
                <form class="navbar-form" action="">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" size="35" placeholder="请输入关键字"
                               maxlength="15" autocomplete="off">
                        <span class="input-group-btn">
		                    <button class="btn btn-default btn-search" type="submit">搜索</button>
		                </span>
                    </div>
                </form>
            </div>
        </div>
        <div class="widget widget_hot">
            <h3>最热评论文章</h3>
            <ul>
                {% for news in hot_news %}
                    <li>
                        <a title="{{ news.title }}" href="/news/{{ news.id }}/">
                            <span class="thumbnail">
				                <img class="thumb" data-original="{{ news.image_url }}"
                                     src="{{ news.image_url }}" alt="{{ news.title }}"
                                     style="display: block;"></span>
                            <span class="text"> {{ news.title }}</span>
                            <span class="muted"><i
                                    class="glyphicon glyphicon-time"></i> {{ news.update_time|time_filter }} </span>
                            <span class="muted"><i
                                    class="glyphicon glyphicon-eye-open"></i> {{ news.clicks }}</span>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </aside>
{% endblock %}
{% block script %}

{% endblock %}